version: "3.3"
services:
  youtrack:
    image: jetbrains/youtrack:2023.1.10168
    container_name: "youtrack"
    volumes:
      - ./data:/opt/youtrack/data
      - ./conf:/opt/youtrack/conf
      - ./logs:/opt/youtrack/logs
      - ./backups:/opt/youtrack/backups
    ports:
      - 8081:8080